> NumPy - Numerical PYthon
1. It`s a library consists of multidimesional array objects

> Numpy vs List

| Feature                | Python List                                        | NumPy Array                                                |
|------------------------|----------------------------------------------------|------------------------------------------------------------|
| **Data Type Support**  | Able to store different data types in the same list| Can store only one data type in an array at any time       |
| **Memory Allocation**  | Items stored in random memory locations            | Items stored sequentially in memory                        |
| **Use Case**           | Good for scenarios where list can grow dynamically | Good for scenarios with fixed-size, same data type elements|
| **Library Requirement**| Inbuilt data type                                  | Requires external NumPy library                            |
| **Functionality**      | Has more inbuilt functions                         | Lightweight with no extra functions (less memory usage)    |


<img src="https://predictivehacks.com/wp-content/uploads/2020/08/numpy_arrays.png">

1. shape(4,)       : 4 columns
2. shape:(2,3)     : 2 rows and 3 colums
3. shape:(4,3,2)   : 4 layers, 3 rows and 2 columns

> Attributes

1. n.dim - to check the dimension
2. .shape - to print the shape
3. .dtype - To check the datatype passed in array
4. type - To check the type of array type(variable name(a))
5. len - To check the length of array len(variable name(a))
6. .arange - like range (1,11) it prints 1 to 10 (start,stop,skip/step)
7. .eye - eye Return a 2D array with ones on the digonal and zeros elsewhere
8. .zeros,.ones,,.full - prints the defined number with dimension
9. .diag - prints the output diagonally & define atleast in 1d np.diag([1,])
10. .reshape - changing the shape (dimensions) of an array without changing its data.
  - Example: An array range (1,13).To reshape what will be possibilities for 12
  - 12 we can reshape into (3,4)(4,3)(1,12)(12,1)(2,6)(6,2)(2,3,2)...
11. np.ravel() - it converts ndimension into 1D
12. np.ravel() - it converts ndimension into 1D
>Differnce b/n ravel and faltten

Changes to ravel() output may affect the original array (if it's a view)	Changes to flatten() output do not affect the original array
13. Indexing
14. Slicing - [rowstart:rowend,col[start]:col[end] & [layerstart:layerend,rowstart:rowend,col[start]:col[end]
> Copy vs View
15. .shares_memory() - Use np.shares_memory(a, b) to check whether two NumPy arrays share the same memory. It returns True if they do, and False otherwise.
16. .view - The view() function creates a new array that shares the same memory, so changes in one array affect the other like ***ravel***.
17. .copy() - The copy() function creates a new array with a different memory location, so changes in the copied array do not affect the original like ***flatten***


In [2]:
# For install numpy
#!pip install numpy
#import numpy module with alias np
import numpy as np

In [ ]:
#APPEND
#Adding the element
element = np.array([1,2,3])
add_element = np.append(element,[4])
print(f"element {element}")
print(f"add_element {add_element}")

In [ ]:
#passing array a list and string
multi_datatype = np.array([1,2,3,4,'aa'])
multi_datatype
#OUTPUT:array(['1', '2', '3', '4', 'aa'], dtype='<U21')
# converted list to string

In [ ]:
#same example tried removing string the output is LIST
list_array = np.array([1,2,3,4])
list_array
#OUTPUT: array([1, 2, 3, 4])

In [ ]:
tuple_array = np.array((1,2,3,4,'aa'))
tuple_array
#OUTPUT:array(['1', '2', '3', '4', 'aa'], dtype='<U21')
# converted tuple into list with strings

In [ ]:
tuple_array = np.array((1,2,3,4))
tuple_array
#OUTPUT:array([1, 2, 3, 4]), dtype='<U21')
# converted tuple into list

In [ ]:
set_array = np.array({1,2,3,4})
set_array
#Output:array({'aa', 2, 3, 4, 1}, dtype=object) printed as set

In [ ]:
dict_array = np.array({1:1,2:2,3:3,4:4,'aa':1})
dict_array
#output:array({1: 1, 2: 2, 3: 3, 4: 4}, dtype=object) printed as dict

In [ ]:
string_date ="hello"
string_array = np.array(list(string_date))
print(f" {string_array}")
whole_string = np.array(string_date)
print(f" {whole_string}")

In [ ]:
list_list = np.array([1,2,3,(1,2)])
list_array
#Output->ERROR->ValueError: setting an array element with a sequence.
# The requested array has an inhomogeneous shape after 1 dimensions.
# The detected shape was (4,) + inhomogeneous part.

> Dimensions in Arrays
1. Numpy array can be of n dimentions
2. Different Dimentions
    1. A numpy array with one single interger 10 - NO Dimention
    2. A numpy array passing a list  having a list = [1,2,3] - One Dimention
    3. nested list having [[1,2,3],[4,5,6]] as elements - Two Dimention
    4. Nested list having [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]] as elements - Three Dimention
    5. ...... n dimentions
    6. we can identify the dimention with no of square brackets "[ ]"

In [ ]:
a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
## TO check the dimension use ndim attributes on each variable
print(f" Dimension a {a.ndim}")
print(f" Dimension b {b.ndim}")
print(f" Dimension c {c.ndim}")
print(f" Dimension d {d.ndim}")

In [ ]:
## print shape of each
print(a)
print(f" shape a {a.shape}")
print("-" * 30)
print(b)
print(f" shape b {b.shape} column")
print("-" * 30)
print(c)
print(f" shape c {c.shape} rows and column")
print("-" * 30)
print(d)
print(f" shape d {d.shape} layers, rows and column")
print("-" * 30)

In [ ]:
# To check the datatype passed in array .dtype
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)


In [ ]:
# To check the type of array type(variable name(a))
print(type(a))
print(type(b))
print(type(c))
print(type(d))

In [20]:
# To check the length of array len(variable name(a))
#print(len(a)) # TypeError: len() of unsized object
print(len(b))
print(len(c))
print(len(d))

NameError: name 'b' is not defined

### why lists are most commonly used to create NumPy arrays.
1. Lists are ordered and structured
Lists maintain order and allow nesting (for 2D, 3D arrays).

You can do things like:

[[1, 2], [3, 4]]  # 2D list
[[[1], [2]], [[3], [4]]]  # 3D list
This structure maps perfectly to how NumPy organizes multi-dimensional arrays.

 2. Lists support mixed and uniform data
While Python lists allow mixed types, we usually use them with consistent types for NumPy.

NumPy automatically infers a consistent dtype from the list.

Example:

import numpy as np
np.array([1, 2, 3])       # → int array
np.array([1.0, 2.0, 3.0]) # → float array

3. Easy to write and read
Lists are:

Simple to type: [1, 2, 3]

Easy to visualize, especially when nested

Familiar to most Python users

This makes lists the default choice when starting with NumPy arrays.

Why not use other types as often?
>Type	     Why it's not ideal for NumPy arrays.

>Tuple	   Immutable, but okay — just less common

>Set	     Unordered and no duplicates — not suitable for structured arrays

>Dict	     Key-value format doesn’t map well to arrays

>String	   Treated as a sequence of characters — only useful in certain cases

Bottom line:
Lists are the most natural and flexible way to create arrays — especially for multidimensional data — and that's why they're used most often.

In [ ]:
# .arange like range function it prints 1 to 10
np.arange(1,11)

In [ ]:
# .arange like range function it prints 1 to 10 and skip/step 2
np.arange(1,11,2)

In [ ]:
#Eye Function
#.eye - eye Return a 2D array with ones on the digonal and zeros elsewhere
np.eye(3, dtype=int)

In [ ]:
#Zero Fuction
zero_1d = np.zeros(3, dtype=int)
print(f"1d_zero {zero_1d}")

zero_2d = np.zeros((3,3),dtype=int)
print(f"2d_zero {zero_2d}")

zero_3d = np.zeros((3,3,3),dtype=int)
print(f"3d_zero {zero_3d}")

In [ ]:
#One FUnction
one_1d = np.ones(3, dtype=int)
print(f"one_1d {one_1d}")

one_2d = np.ones((3,3),dtype=int)
print(f"one_2d {one_2d}")

one_3d = np.ones((3,3,3),dtype=int)
print(f"one_3d {one_3d}")

In [ ]:
#Full Function
full_id = np.full((3),5,dtype=int)
print(f"full_id {full_id} \n { '-' * 40}")

full_2d = np.full((3,3),5,dtype=int)
print(f"full_2d {full_2d}")

In [236]:
#diag function
diag_fun = np.diag([1,2,3,4])
print(f"diag_fun \n {diag_fun}")

diag_fun1=np.diag([1,]) # we should always define atleast in 1d
print(diag_fun1)

diag_fun 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[1]]


### reshape, ravel,flatten
- .reshape - changing the shape (dimensions) of an array without changing its data.
  - Example: An array range (1,13).To reshape what will be possibilities for 12
  - 12 we can reshape into (3,4)(4,3)(1,12)(12,1)(2,6)(6,2)(2,3,2)...
- np.ravel() - it converts ndimension into 1D
- np.ravel() - it converts ndimension into 1D
>Differnce b/n ravel and faltten

Changes to ravel() output may affect the original array (if it's a view)	Changes to flatten() output do not affect the original array

In [ ]:
#.reshape - Reshaping means changing the shape of a array(12)
reshape_ex = np.arange(1,13)
print(reshape_ex)
print(reshape_ex.shape)
print(reshape_ex.ndim)

In [ ]:
reshape_ex_1 = reshape_ex.reshape((4,3))
print(reshape_ex_1.shape)
print(reshape_ex_1.ndim)
print(f"reshape_ex_1 \n {reshape_ex_1} \n { '-' * 40}")
reshape_ex_2 = reshape_ex.reshape((3,4))
print(reshape_ex_2.shape)
print(reshape_ex_2.ndim)
print(f"reshape_ex_2 \n {reshape_ex_2} \n { '-' * 40}")
reshape_ex_3 = reshape_ex.reshape((2,3,2))
print(reshape_ex_3.shape)
print(reshape_ex_3.ndim)
print(f"reshape_ex_3 \n {reshape_ex_3} \n { '-' * 40}")

In [ ]:
#np.ravel() - it converts ndimension into 1D
ravel_ex = np.ravel(reshape_ex_3)
print(ravel_ex)
print(ravel_ex.ndim)
print(ravel_ex.shape)



In [ ]:
#flatten(Converst array into 1D)
flatten_ex = reshape_ex_3.flatten()
print(flatten_ex)
print(flatten_ex.ndim)
print(flatten_ex.shape)

In [ ]:
diff_rav_fal = np.array([[3,2],[4,5]])
print(diff_rav_fal.ndim)
print(diff_rav_fal.shape)
print(f"diff_rav_fal \n {diff_rav_fal} \n { '-' * 40}")
diff_rav= np.ravel(diff_rav_fal)
print(diff_rav.ndim)
print(diff_rav.shape)
print(f"diff_rav \n {diff_rav} \n { '-' * 40}")
diff_fal = diff_rav_fal.flatten()
print(diff_fal.ndim)
print(diff_fal.shape)
print(f"diff_fal \n {diff_fal} \n { '-' * 40}")
#changing the array
diff_rav_fal[0,0] = 100
print(f"diff_rav_fal \n {diff_rav_fal} \n { '-' * 40}")
print(f"diff_rav \n {diff_rav} \n { '-' * 40}")
print(f"diff_fal \n {diff_fal} \n { '-' * 40}")

### *NUMPY INDEXING*

In [22]:
index_1 = np.array([2,5,6,3,18,19,30,40])
print(index_1)
print(index_1[3])
print(index_1[6])
print(index_1[0:30:2])
update_index = index_1[5]=100
print(update_index)
print(index_1)

[ 2  5  6  3 18 19 30 40]
3
30
[ 2  6 18 30]
100
[  2   5   6   3  18 100  30  40]


In [23]:
index_2 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(index_2)
print(index_2[1,1])
print(index_2[2,2])
print(index_2[0:9,2]) #value of 2 is column
update_index_2 = index_2[1,2]=200 #(0,0)(0,1)(0,2)
print(update_index_2)
print(index_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
9
[3 6 9]
200
[[  1   2   3]
 [  4   5 200]
 [  7   8   9]]


In [24]:
index_3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(index_3)
print(index_3[0][1][1])  #extact value
print(index_3[1,1,1])
update_index3 = index_3[1,1,1] = 1100
print(update_index3)
print(index_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
5
11
1100
[[[   1    2    3]
  [   4    5    6]]

 [[   7    8    9]
  [  10 1100   12]]]


### *NUMPY SLICING*
- [rowstart:rowend,col[start]:col[end]
- [layerstart:layerend,rowstart:rowend,col[start]:col[end]

In [ ]:
slicing_1 = np.arange(1,11) # START:STOP:STEP/SKIP
print(slicing_1)
print(slicing_1[8])
print(slicing_1[5:])
print(slicing_1[0:6])
print(slicing_1[0:10:3])
print(f"{'*'* 20} 1d slicing {'*'* 20}")
slicing_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(slicing_2)
print(slicing_2[1,1])
#[rowstart:rowend,col[start]:col[end]
print(slicing_2[0:3,0:2])
print(f"slicing_2[:,1] col = {slicing_2[:,1]}")
print(f"slicing_2[1,:] row = {slicing_2[1,:]}")
print(slicing_2[:,1:3])
print(f"{'*'* 20} 2d slicing {'*'* 20}")
#[layerstart:layerend,rowstart:rowend,col[start]:col[end]
slicing_3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f"slicing_3 \n {slicing_3} \n { '-' * 40}")
print(f"slicing_3[1] \n {slicing_3[1]}\n")
print(slicing_3[1,1:])
print(slicing_3[:,0,1])
print(slicing_3[:,:,0])
print(slicing_3[1,0:1,1])
print(f"{'*'* 20} 3d slicing {'*'* 20}")

### NumPy Copy vs View
- .shares_memory() - Use np.shares_memory(a, b) to check whether two NumPy arrays share the same memory. It returns True if they do, and False otherwise.
- .view - The view() function creates a new array that shares the same memory, so changes in one array affect the other like ***flattern***.
- .copy() - The copy() function creates a new array with a different memory location, so changes in the copied array do not affect the original like ***ravel***

In [10]:
x1 = np.arange(11,55,4)
print(x1)

[100  15  19  23  27  31  35  39  43  47  51]


In [11]:
#assign
x2 = x1 #view
print(x1)
print(x2)

[11 15 19 23 27 31 35 39 43 47 51]
[11 15 19 23 27 31 35 39 43 47 51]


In [12]:
#change the element of copy_vs_view_1 as 10
x2[0] = 100
print(x1)
print(x2)

[100  15  19  23  27  31  35  39  43  47  51]
[100  15  19  23  27  31  35  39  43  47  51]


In [13]:
print(id(x1))
print(id(x2))

139203740127792
139203740127792


In [14]:
#shares_memory()
# To check the variables whether share the memory or not
print(np.shares_memory(x1,x2))

True


In [17]:
#.view function
print(x2)
x3 = x2.view()
print(x3)
view_share_memory = np.shares_memory(x2,x3)
print(f"view_share_memory is : {view_share_memory}") # it shared same memory

[100  15  19  23  27  31  35  39  43  47  51]
[100  15  19  23  27  31  35  39  43  47  51]
view_share_memory is : True


In [18]:
#.copy() - It will copy the variable. But, the memeory location will be differnt.
x4 = x1.copy()
print(x1)
print(x4)
print(id(x1)) # the memory location is different
print(id(x4))

[100  15  19  23  27  31  35  39  43  47  51]
[100  15  19  23  27  31  35  39  43  47  51]
139203740127792
139204157378544


In [19]:
 # if you create a copy of an array using the copy() function, changing an element in the copied array does not affect the original array, because they are stored in different memory locations.
x4[0]= 999
print(x4)
print(x1)

[999  15  19  23  27  31  35  39  43  47  51]
[100  15  19  23  27  31  35  39  43  47  51]


In [21]:
print(np.shares_memory(x1,x4))

False


### Operations on NumPy
- .T - Transpose means flipping the dimensions of an array — converting rows into columns and columns into rows.
> hstack and vstack function
- Stacking is same as concatenation, the only differnce is that stacking is done along a new axis
- .hstack - to stack along rows
- .vstack = to stack along cloumns

In [25]:
operations = np.array([[1,2,3,],[4,5,6],[7,8,9]])
operations

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
operations > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [31]:
#It get the list of elements
operations[operations > 3]

array([4, 5, 6, 7, 8, 9])

In [32]:
operations[(operations > 3) & (operations < 8)]

array([4, 5, 6, 7])

Transpose - Transpose means flipping the dimensions of an array — converting rows into columns and columns into rows.

In [33]:
#Transpose - Transpose means flipping the dimensions of an array — converting rows into columns and columns into rows.
transpose_1 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(transpose_1)
transpose_1.T

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

> hstack and vstack function
- Stacking is same as concatenation, the only differnce is that stacking is done along a new axis
- .hstack - to stack along rows
- .vstack = to stack along cloumns

In [38]:
print(x1)
print(x2)

[100  15  19  23  27  31  35  39  43  47  51]
[100  15  19  23  27  31  35  39  43  47  51]


In [39]:
np.vstack((x1,x2))

array([[100,  15,  19,  23,  27,  31,  35,  39,  43,  47,  51],
       [100,  15,  19,  23,  27,  31,  35,  39,  43,  47,  51]])

In [40]:
np.hstack((x1,x2))

array([100,  15,  19,  23,  27,  31,  35,  39,  43,  47,  51, 100,  15,
        19,  23,  27,  31,  35,  39,  43,  47,  51])

In [41]:
array2 = np.array([1,2,3,4,5,6,7,8])
np.vstack(array2)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [44]:
array3 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(array3)
print(np.hstack(array3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


Adding, Insert and Delete NumPy Array

In [1]:
import numpy as np
array_add = np.array([1,2,3,4,5])
print(array_add)
new_array_add = np.insert(array_add,3,100) # Insert 100 at index 3
print(new_array_add)

[1 2 3 4 5]
[  1   2   3 100   4   5]
