
> ## NumPy - Numerical PYthon  
1. It's a library consisting of multidimensional array objects.

---

> ## NumPy vs List

| Feature                | Python List                                        | NumPy Array                                                |
|------------------------|----------------------------------------------------|------------------------------------------------------------|
| **Data Type Support**  | Able to store different data types in the same list| Can store only one data type in an array at any time       |
| **Memory Allocation**  | Items stored in random memory locations            | Items stored sequentially in memory                        |
| **Use Case**           | Good for scenarios where list can grow dynamically | Good for scenarios with fixed-size, same data type elements|
| **Library Requirement**| Inbuilt data type                                  | Requires external NumPy library                            |
| **Functionality**      | Has more inbuilt functions                         | Lightweight with no extra functions (less memory usage)    |

<img src="https://predictivehacks.com/wp-content/uploads/2020/08/numpy_arrays.png" alt="NumPy Arrays">

---

> ## Array Shapes

1. `shape(4,)`       → 1D array with 4 columns  
2. `shape(2, 3)`     → 2 rows and 3 columns  
3. `shape(4, 3, 2)`  → 4 layers, 3 rows, 2 columns  

---

> ## Key NumPy Attributes & Methods

| No. | Attribute / Method     | Description |
|-----|------------------------|-------------|
| 1.  | `.ndim`                | Check the number of dimensions |
| 2.  | `.shape`               | Print the shape of the array |
| 3.  | `.dtype`               | Check the data type of the array |
| 4.  | `type()`               | Check the type of the array (e.g. `<class 'numpy.ndarray'>`) |
| 5.  | `len()`                | Length of the array |
| 6.  | `np.arange(start, stop, step)` | Like Python `range()` but returns an array |
| 7.  | `np.eye(n)`            | Returns a 2D array with 1s on the diagonal, 0s elsewhere |
| 8.  | `np.zeros`, `np.ones`, `np.full` | Generate arrays filled with specified values |
| 9.  | `np.diag([values])`    | Creates a diagonal matrix |
| 10. | `.reshape()`           | Change the shape without changing data |
|     |                        | Example reshapes for 12 elements: `(3,4)`, `(4,3)`, `(2,6)`, `(6,2)`, `(2,3,2)` |
| 11. | `np.ravel()`           | Flattens n-dimensional array to 1D (returns view if possible) |
| 12. | `flatten()`            | Flattens n-dimensional array to 1D (always returns a copy) |

---

> ## 🔁 Ravel vs Flatten

- `ravel()` → Changes **may** affect original (returns **view**)
- `flatten()` → Changes **do not** affect original (returns **copy**)

---

> ## Indexing and Slicing

- Slicing syntax: `[row_start:row_end, col_start:col_end]`
- 3D Slicing: `[layer_start:layer_end, row_start:row_end, col_start:col_end]`

---

> ## Copy vs View

| Concept      | Description |
|--------------|-------------|
| `.copy()`    | Creates a new array in a **different memory location**. Changes do **not** affect original. *(Like `flatten`)* |
| `.view()`    | Creates a new array **sharing the same memory**. Changes **do** affect original. *(Like `ravel`)* |
| `np.shares_memory(a, b)` | Returns `True` if two arrays share the same memory |


In [ ]:
# For install numpy
#!pip install numpy
#import numpy module with alias np
import numpy as np

In [ ]:
#APPEND
#Adding the element
element = np.array([1,2,3])
add_element = np.append(element,[4])
print(f"element {element}")
print(f"add_element {add_element}")

In [ ]:
#passing array a list and string
multi_datatype = np.array([1,2,3,4,'aa'])
multi_datatype
#OUTPUT:array(['1', '2', '3', '4', 'aa'], dtype='<U21')
# converted list to string

In [ ]:
#same example tried removing string the output is LIST
list_array = np.array([1,2,3,4])
list_array
#OUTPUT: array([1, 2, 3, 4])

In [ ]:
tuple_array = np.array((1,2,3,4,'aa'))
tuple_array
#OUTPUT:array(['1', '2', '3', '4', 'aa'], dtype='<U21')
# converted tuple into list with strings

In [ ]:
tuple_array = np.array((1,2,3,4))
tuple_array
#OUTPUT:array([1, 2, 3, 4]), dtype='<U21')
# converted tuple into list

In [ ]:
set_array = np.array({1,2,3,4})
set_array
#Output:array({'aa', 2, 3, 4, 1}, dtype=object) printed as set

In [ ]:
dict_array = np.array({1:1,2:2,3:3,4:4,'aa':1})
dict_array
#output:array({1: 1, 2: 2, 3: 3, 4: 4}, dtype=object) printed as dict

In [ ]:
string_date ="hello"
string_array = np.array(list(string_date))
print(f" {string_array}")
whole_string = np.array(string_date)
print(f" {whole_string}")

In [ ]:
list_list = np.array([1,2,3,(1,2)])
list_array
#Output->ERROR->ValueError: setting an array element with a sequence.
# The requested array has an inhomogeneous shape after 1 dimensions.
# The detected shape was (4,) + inhomogeneous part.

### Dimensions in Arrays
1. Numpy array can be of n dimentions
2. Different Dimentions
    1. A numpy array with one single interger 10 - NO Dimention
    2. A numpy array passing a list  having a list = [1,2,3] - One Dimention
    3. nested list having [[1,2,3],[4,5,6]] as elements - Two Dimention
    4. Nested list having [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]] as elements - Three Dimention
    5. ...... n dimentions
    6. we can identify the dimention with no of square brackets "[ ]"

In [ ]:
a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
## TO check the dimension use ndim attributes on each variable
print(f" Dimension a {a.ndim}")
print(f" Dimension b {b.ndim}")
print(f" Dimension c {c.ndim}")
print(f" Dimension d {d.ndim}")

In [ ]:
## print shape of each
print(a)
print(f" shape a {a.shape}")
print("-" * 30)
print(b)
print(f" shape b {b.shape} column")
print("-" * 30)
print(c)
print(f" shape c {c.shape} rows and column")
print("-" * 30)
print(d)
print(f" shape d {d.shape} layers, rows and column")
print("-" * 30)

In [ ]:
# To check the datatype passed in array .dtype
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)


In [ ]:
# To check the type of array type(variable name(a))
print(type(a))
print(type(b))
print(type(c))
print(type(d))

In [ ]:
# To check the length of array len(variable name(a))
#print(len(a)) # TypeError: len() of unsized object
print(len(b))
print(len(c))
print(len(d))

### why lists are most commonly used to create NumPy arrays.
1. Lists are ordered and structured
  Lists maintain order and allow nesting (for 2D, 3D arrays).

  You can do things like:

  [[1, 2], [3, 4]]  # 2D list
  [[[1], [2]], [[3], [4]]]  # 3D list
  This structure maps perfectly to how NumPy organizes multi-dimensional arrays.

2. Lists support mixed and uniform data
  While Python lists allow mixed types, we usually use them with consistent types for NumPy.

  NumPy automatically infers a consistent dtype from the list.

  Example:

  import numpy as np
  np.array([1, 2, 3])       # → int array
  np.array([1.0, 2.0, 3.0]) # → float array

3. Easy to write and read
  Lists are:

  Simple to type: [1, 2, 3]

  Easy to visualize, especially when nested

  Familiar to most Python users

  This makes lists the default choice when starting with NumPy arrays.

  Why not use other types as often?
  >Type	     Why it's not ideal for NumPy arrays.

  >Tuple	   Immutable, but okay — just less common

  >Set	     Unordered and no duplicates — not suitable for structured arrays

  >Dict	     Key-value format doesn’t map well to arrays

  >String	   Treated as a sequence of characters — only useful in certain cases

  Bottom line:
  Lists are the most natural and flexible way to create arrays — especially for multidimensional data — and that's why they're used most often.

In [ ]:
# .arange like range function it prints 1 to 10
np.arange(1,11)

In [ ]:
# .arange like range function it prints 1 to 10 and skip/step 2
np.arange(1,11,2)

In [ ]:
#Eye Function
#.eye - eye Return a 2D array with ones on the digonal and zeros elsewhere
np.eye(3, dtype=int)

In [ ]:
#Zero Fuction
zero_1d = np.zeros(3, dtype=int)
print(f"1d_zero {zero_1d}")

zero_2d = np.zeros((3,3),dtype=int)
print(f"2d_zero {zero_2d}")

zero_3d = np.zeros((3,3,3),dtype=int)
print(f"3d_zero {zero_3d}")

In [ ]:
#One FUnction
one_1d = np.ones(3, dtype=int)
print(f"one_1d {one_1d}")

one_2d = np.ones((3,3),dtype=int)
print(f"one_2d {one_2d}")

one_3d = np.ones((3,3,3),dtype=int)
print(f"one_3d {one_3d}")

In [ ]:
#Full Function
full_id = np.full((3),5,dtype=int)
print(f"full_id {full_id} \n { '-' * 40}")

full_2d = np.full((3,3),5,dtype=int)
print(f"full_2d {full_2d}")

In [ ]:
#diag function
diag_fun = np.diag([1,2,3,4])
print(f"diag_fun \n {diag_fun}")

diag_fun1=np.diag([1,]) # we should always define atleast in 1d
print(diag_fun1)

### reshape, ravel,flatten
- .reshape - changing the shape (dimensions) of an array without changing its data.
  - Example: An array range (1,13).To reshape what will be possibilities for 12
  - 12 we can reshape into (3,4)(4,3)(1,12)(12,1)(2,6)(6,2)(2,3,2)...
- np.ravel() - it converts ndimension into 1D
- np.ravel() - it converts ndimension into 1D
>Differnce b/n ravel and faltten

Changes to ravel() output may affect the original array (if it's a view)	Changes to flatten() output do not affect the original array

In [ ]:
#.reshape - Reshaping means changing the shape of a array(12)
reshape_ex = np.arange(1,13)
print(reshape_ex)
print(reshape_ex.shape)
print(reshape_ex.ndim)

In [ ]:
reshape_ex_1 = reshape_ex.reshape((4,3))
print(reshape_ex_1.shape)
print(reshape_ex_1.ndim)
print(f"reshape_ex_1 \n {reshape_ex_1} \n { '-' * 40}")
reshape_ex_2 = reshape_ex.reshape((3,4))
print(reshape_ex_2.shape)
print(reshape_ex_2.ndim)
print(f"reshape_ex_2 \n {reshape_ex_2} \n { '-' * 40}")
reshape_ex_3 = reshape_ex.reshape((2,3,2))
print(reshape_ex_3.shape)
print(reshape_ex_3.ndim)
print(f"reshape_ex_3 \n {reshape_ex_3} \n { '-' * 40}")

In [ ]:
#np.ravel() - it converts ndimension into 1D
ravel_ex = np.ravel(reshape_ex_3)
print(ravel_ex)
print(ravel_ex.ndim)
print(ravel_ex.shape)



In [ ]:
#flatten(Converst array into 1D)
flatten_ex = reshape_ex_3.flatten()
print(flatten_ex)
print(flatten_ex.ndim)
print(flatten_ex.shape)

In [ ]:
diff_rav_fal = np.array([[3,2],[4,5]])
print(diff_rav_fal.ndim)
print(diff_rav_fal.shape)
print(f"diff_rav_fal \n {diff_rav_fal} \n { '-' * 40}")
diff_rav= np.ravel(diff_rav_fal)
print(diff_rav.ndim)
print(diff_rav.shape)
print(f"diff_rav \n {diff_rav} \n { '-' * 40}")
diff_fal = diff_rav_fal.flatten()
print(diff_fal.ndim)
print(diff_fal.shape)
print(f"diff_fal \n {diff_fal} \n { '-' * 40}")
#changing the array
diff_rav_fal[0,0] = 100
print(f"diff_rav_fal \n {diff_rav_fal} \n { '-' * 40}")
print(f"diff_rav \n {diff_rav} \n { '-' * 40}")
print(f"diff_fal \n {diff_fal} \n { '-' * 40}")

### *NUMPY INDEXING*

In [ ]:
index_1 = np.array([2,5,6,3,18,19,30,40])
print(index_1)
print(index_1[3])
print(index_1[6])
print(index_1[0:30:2])
update_index = index_1[5]=100
print(update_index)
print(index_1)

In [ ]:
index_2 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(index_2)
print(index_2[1,1])
print(index_2[2,2])
print(index_2[0:9,2]) #value of 2 is column
update_index_2 = index_2[1,2]=200 #(0,0)(0,1)(0,2)
print(update_index_2)
print(index_2)

In [ ]:
index_3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(index_3)
print(index_3[0][1][1])  #extact value
print(index_3[1,1,1])
update_index3 = index_3[1,1,1] = 1100
print(update_index3)
print(index_3)

### *NUMPY SLICING*
- [rowstart:rowend,col[start]:col[end]
- [layerstart:layerend,rowstart:rowend,col[start]:col[end]

In [ ]:
slicing_1 = np.arange(1,11) # START:STOP:STEP/SKIP
print(slicing_1)
print(slicing_1[8])
print(slicing_1[5:])
print(slicing_1[0:6])
print(slicing_1[0:10:3])

In [ ]:
slicing_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(slicing_2)
print(slicing_2[1,1])
#[rowstart:rowend,col[start]:col[end]
print(slicing_2[0:3,0:2])
print(f"slicing_2[:,1] col = {slicing_2[:,1]}")
print(f"slicing_2[1,:] row = {slicing_2[1,:]}")
print(slicing_2[:,1:3])
print(f"{'*'* 20} 2d slicing {'*'* 20}")

In [ ]:
#[layerstart:layerend,rowstart:rowend,col[start]:col[end]
slicing_3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f"slicing_3 \n {slicing_3} \n { '-' * 40}")
print(f"slicing_3[1] \n {slicing_3[1]}\n")
print(slicing_3[1,1:])
print(slicing_3[:,0,1])
print(slicing_3[:,:,0])
print(slicing_3[1,0:1,1])

### NumPy Copy vs View
- .shares_memory() - Use np.shares_memory(a, b) to check whether two NumPy arrays share the same memory. It returns True if they do, and False otherwise.
- .view - The view() function creates a new array that shares the same memory, so changes in one array affect the other like ***flattern***.
- .copy() - The copy() function creates a new array with a different memory location, so changes in the copied array do not affect the original like ***ravel***

In [ ]:
x1 = np.arange(11,55,4)
print(x1)

In [ ]:
#assign
x2 = x1 #view
print(x1)
print(x2)

In [ ]:
#change the element of copy_vs_view_1 as 10
x2[0] = 100
print(x1)
print(x2)

In [ ]:
print(id(x1))
print(id(x2))

In [ ]:
#shares_memory()
# To check the variables whether share the memory or not
print(np.shares_memory(x1,x2))

In [ ]:
#.view function
print(x2)
x3 = x2.view()
print(x3)
view_share_memory = np.shares_memory(x2,x3)
print(f"view_share_memory is : {view_share_memory}") # it shared same memory

In [ ]:
#.copy() - It will copy the variable. But, the memeory location will be differnt.
x4 = x1.copy()
print(x1)
print(x4)
print(id(x1)) # the memory location is different
print(id(x4))

In [ ]:
 # if you create a copy of an array using the copy() function, changing an element in the copied array does not affect the original array, because they are stored in different memory locations.
x4[0]= 999
print(x4)
print(x1)

In [ ]:
print(np.shares_memory(x1,x4))

### Operations on NumPy
- .T - Transpose means flipping the dimensions of an array — converting rows into columns and columns into rows.
> hstack and vstack function
- Stacking is same as concatenation, the only differnce is that stacking is done along a new axis
- .hstack - to stack along rows
- .vstack = to stack along cloumns

In [ ]:
operations = np.array([[1,2,3,],[4,5,6],[7,8,9]])
operations

In [ ]:
operations > 3

In [ ]:
#It get the list of elements
operations[operations > 3]

In [ ]:
operations[(operations > 3) & (operations < 8)]

Transpose - Transpose means flipping the dimensions of an array — converting rows into columns and columns into rows.

In [ ]:
#Transpose - Transpose means flipping the dimensions of an array — converting rows into columns and columns into rows.
transpose_1 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(transpose_1)
transpose_1.T

> hstack and vstack function
- Stacking is same as concatenation, the only differnce is that stacking is done along a new axis
- .hstack - to stack along rows
- .vstack = to stack along cloumns

In [ ]:
print(x1)
print(x2)

In [ ]:
print(x1)
print(x2)

In [ ]:
np.vstack((x1,x2))

In [ ]:
#hstack
np.hstack((x1,x2))

In [ ]:
array2 = np.array([1,2,3,4,5,6,7,8])
np.vstack(array2)

In [ ]:
array3 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(array3)
print(np.hstack(array3))

### Adding, Insert and Delete NumPy Array
- np.insert - To insert the elements accroding to the index.
- np.delete - Delete the elementts
- np.append - Elements will be add at last
  - in 2D (rows,columns) ***INSERT/DELETE ARRAY***
    - axis = 0 Add/Removes in rows
    - axis = 1 Add/Removes in column
  - in 3D (layers,rows,column) ***INSERT/DELETE ARRAY***
    - axis = 0 Add/Removes layers
    - axis = 1 Add/Removes row in each layer
    - axis = 2 Add/Removes column in each layer
- np.concatenate - Most flexible and general-puporse. We must manully specify the axis to join. Doesn`t not add a new axis (unlike stack)

In [ ]:
import numpy as np
array_add = np.array([1,2,3,4,5])
print(array_add)
new_array_add = np.insert(array_add,3,100) # Insert 100 at index 3
print(new_array_add)

In [ ]:
array_add_2 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(array_add_2)
new_array_add_2 = np.insert(array_add_2,1,[33,44,55], axis=0) # axis= 0 Add as a row
print(new_array_add_2)

In [ ]:
array_add_3 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(array_add_3)
new_array_add_3 = np.insert(array_add_2,1,[99,100,55], axis=1) # axis= 1 Add as a column
print(new_array_add_3)

In [ ]:
array_add_4 = np.arange(8).reshape(2,2,2)
print(array_add_4.shape)
print(f"{array_add_4} \n {'-' * 40}")
new_array_add_4 = np.insert(array_add_4,1,[[[99,100],[34,78]]], axis=0) # axis= 0 Add as a layer
print(new_array_add_4)
print(array_add_4.ndim)
print(array_add_4.shape)

In [ ]:
array_add_5 = np.insert(array_add_4,1,[[[99,100],[34,78]]], axis=1) # axis= 0 Add as a rows
print(array_add_5)
print(array_add_5.ndim)
print(array_add_5.shape)

In [ ]:
array_add_6 = np.insert(array_add_4,1,[[[99,100],[34,78]]], axis=2) # axis= 0 Add as a columns
print(array_add_6)
print(array_add_6.ndim)
print(array_add_6.shape)

In [ ]:
#1D DELETE
array_delete = np.arange(1,9)
print(f"{array_delete}\n {'-' * 40}")
array_delete_1 = np.delete(array_delete,3) # INDex 3 will get delete
print(array_delete_1)

In [ ]:
#2D DELETE
array_delete_2 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(array_delete_2)
print(f"{array_delete_2.shape} \n {'-' * 40}")
array_delete_3 =np.delete(array_delete_2,1,axis=0)
print(array_delete_3)
print(array_delete_3.shape)
# 1 is index of rows which is 0,1,2 and axis= 0 is row and axis=1 is column

In [ ]:
#3D DELETE
array_delete_4 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array_delete_4)
print(f"{array_delete_4.shape}\n {'-' * 40}")
array_delete_5 =np.delete(array_delete_4,1,axis=2)
print(array_delete_5)
print(array_delete_5.shape)
# changing the 1 and the axis the result will vary

In [ ]:
# 1D APPEND
array_append = np.array([1,2,3,4,5,6,7,8,9])
print(array_append)
print(f"{array_append.shape}\n {'-' * 40}")
array_append_1 = np.append(array_append,[10,11])
print(array_append_1)
print(f"{array_append_1.shape}\n {'-' * 40}")

In [ ]:
#2D APPEND
array_append_2 = np.array([[1,2,],[4,5],[7,8]])
print(array_append_2)
print(f"{array_append_2.shape}\n {'-' * 40}")
array_append_3 = np.append(array_append_2,[[10,11]],axis=0)
print(array_append_3)
print(f"{array_append_3.shape}\n {'-' * 40}")

In above example when we change the axis=1 (it will add as column)we got VALUE ERROR due to no of elements/index. If we check with below example we mention matching element/index it is working

In [ ]:
#2D APPEND
array_append_2 = np.array([[1,2,],[5,6],[9,10]])
print(array_append_2)
print(f"{array_append_2.shape}\n {'-' * 40}")
array_append_3 = np.append(array_append_2,[[3,4],[7,8],[11,12]],axis=1)
print(array_append_3)
print(f"{array_append_3.shape}\n {'-' * 40}")
array_append_4 = np.append(array_append_2,[[3],[6],[9]],axis=1)
print(array_append_4)
print(f"{array_append_4.shape}\n {'-' * 40}")

In [ ]:
#3D APPEND
array_append_4 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array_append_4)
print(f"{array_append_4.shape}\n {'-' * 40}")
# To append along axis=1, the new array must have the same number of layers as the original array
array_to_append = np.array([[[13,14,15]], [[16,17,18]]])
array_append_5 = np.append(array_append_4, array_to_append, axis=1)
print(array_append_5)
print(f"{array_append_5.shape}\n {'-' * 40}")

CONCATENATE

In [82]:
#1D CONCATNEATE
concat = np.array([1,2])
print(f"{concat}\n {'-' * 40}")
concat_1 = np.array([3,4])
print(f"{concat_1} \n {'-' * 40}")
concat_array = np.concatenate((concat,concat_1))
print(concat_array)

[1 2]
 ----------------------------------------
[3 4] 
 ----------------------------------------
[1 2 3 4]


In [89]:
#2D CONCATNEATE
concat_2 = np.array([[1,2,3],[4,5,6]])
print(f"{concat_2}\n {'-' * 40}")
concat_3 = np.array([[7,8,9]])
print(f"{concat_3} \n {'-' * 40}")
concat_array_2 = np.concatenate((concat_2,concat_3),axis=0)
print(concat_array_2)
# Again if we change to axis=1(which is column) we get VALUE ERROR the elemnts/index should be same in both concat_2 and concat_3

[[1 2 3]
 [4 5 6]]
 ----------------------------------------
[[7 8 9]] 
 ----------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [98]:
#3D CONCATNEATE
concat_4 = np.array([[[1,2],[3,4]]])
print(f"{concat_4}\n {'-' * 40}")
concat_5 = np.array([[[5,6],[7,8]]])
print(f"{concat_5} \n {'-' * 40}")
concat_array_3 = np.concatenate((concat_4,concat_5),axis=0)
print(f"axis = 0(Layer) :\n {concat_array_3} \n {'-' * 40}")
concat_array_3 = np.concatenate((concat_4,concat_5),axis=1)
print(f"axis = 1(row) :\n {concat_array_3} \n {'-' * 40}")
concat_array_3 = np.concatenate((concat_4,concat_5),axis=2)
print(f"axis = 2(columns) :\n {concat_array_3} \n {'-' * 40}")

[[[1 2]
  [3 4]]]
 ----------------------------------------
[[[5 6]
  [7 8]]] 
 ----------------------------------------
axis = 0(Layer) :
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 
 ----------------------------------------
axis = 1(row) :
 [[[1 2]
  [3 4]
  [5 6]
  [7 8]]] 
 ----------------------------------------
axis = 2(columns) :
 [[[1 2 5 6]
  [3 4 7 8]]] 
 ----------------------------------------


STACK
- np.stack() Adds a new axis - increases dimesionality. All input arrays must have exact same shape

In [103]:
#1D
stack_1 = np.array([1,2])
print(f"{stack_1}\n {'-' * 40}")
print(f"{stack_1.ndim}\n {'-' * 40}")
stack_2 = np.array([3,4])
print(f"{stack_1}\n {'-' * 40}")
print(f"{stack_2.ndim}\n {'-' * 40}")
stack_array = np.stack((stack_1,stack_2))
print(stack_array)
print(f"{stack_array.ndim}\n {'-' * 40}")
# Changed/converted to 2D

[1 2]
 ----------------------------------------
1
 ----------------------------------------
[1 2]
 ----------------------------------------
1
 ----------------------------------------
[[1 2]
 [3 4]]
2
 ----------------------------------------


In [106]:
#2D
stack_3 = np.array([[1,2,3],[4,5,6]])
print(f"{stack_3}\n {'-' * 40}")
stack_4 = np.array([[7,8,9],[10,11,12]]) #SAME ELEMENTS
print(f"{stack_4} \n {'-' * 40}")
stack_array_1 = np.stack((stack_3,stack_4),axis=0)
print(stack_array_1)
print(stack_array_1.ndim)

[[1 2 3]
 [4 5 6]]
 ----------------------------------------
[[ 7  8  9]
 [10 11 12]] 
 ----------------------------------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [119]:
#3D
stack_5 = np.array([[[1,2,3],[4,5,6]]])
print(f"{stack_5}\n {'-' * 40}")
print(f"{stack_5.ndim}\n {'-' * 40}")
stack_6 = np.array([[[7,8,9],[10,11,12]]])
print(f"{stack_6} \n {'-' * 40}")
print(f"{stack_6.ndim}\n {'-' * 40}")
stack_array_2 = np.stack((stack_5,stack_6),axis=0)
print(stack_array_2)
print(stack_array_2.ndim)

[[[1 2 3]
  [4 5 6]]]
 ----------------------------------------
3
 ----------------------------------------
[[[ 7  8  9]
  [10 11 12]]] 
 ----------------------------------------
3
 ----------------------------------------
[[[[ 1  2  3]
   [ 4  5  6]]]


 [[[ 7  8  9]
   [10 11 12]]]]
4


In [ ]:
#When to Use What?
#Use Case	                               Use This
#Combine 1D arrays side by side	            hstack
#Stack 2D arrays vertically	                vstack
#Add a new dimension to the array	          stack
#Combine along custom axis	             concatenate

## Common Aggregate Functions in NumPy

In [ ]:
#Function	    1D Output	             2D (axis=0)	            3D (axis=0)
#np.sum	       Total	              Sum of columns	         Sum of slices
#np.min	       Minimum      	       Min of columns	         Min of slices
#np.max	       Maximum          	   Max of columns	         Max of slices
#np.cumsum	  Cumulative sum	     Cumulative down rows	  Cumulative down slices
#np.cumprod	  Cumulative product	 Cumulative down rows	  Cumulative down slices

In [121]:
import numpy as np
#1D
sum_1 = np.array([1,2])
sum_array = np.sum(sum_1)
print(sum_array)

3


In [124]:
min_1 = np.arange(8)
print(min_1)
minarray =  np.min(min_1)
print(minarray)

[0 1 2 3 4 5 6 7]
0


In [127]:
max_1 = np.arange(8)
print(max_1)
max_array = np.max(max_1)
print(max_array)

[0 1 2 3 4 5 6 7]
7


In [129]:
cumsum_1 = np.arange(8) # addition
print(cumsum_1)
cumsum_array = np.cumsum(cumsum_1)
print(cumsum_array)

[0 1 2 3 4 5 6 7]
[ 0  1  3  6 10 15 21 28]


In [134]:
cumprod_1 = np.arange(1,10) #mulitplication
print(cumprod_1)
cumprod_array = np.cumprod(cumprod_1)
print(cumprod_array)

[1 2 3 4 5 6 7 8 9]
[     1      2      6     24    120    720   5040  40320 362880]


# 📚 Axis Meaning in 2D NumPy Arrays

In a 2D NumPy array, axes define the direction in which operations are applied:

## 🔄 Axis Definitions

| Axis   | Operates Along       | Affects         | Description         |
|--------|-----------------------|------------------|----------------------|
| `0`    | Down the rows         | Across columns   | Operates column-wise |
| `1`    | Across the columns    | Across rows      | Operates row-wise    |

## 🧭 Visual Understanding

- `axis=0` → Combines values **vertically** (down each column)
- `axis=1` → Combines values **horizontally** (across each row)

In [146]:
#2D
sum_2 = np.array([[1,2],[3,4]]) # Sequncelly got added
print(sum_2)
sum_array_1 = np.sum(sum_2)
print(f"{sum_array_1} \n {'-' * 40}")
sum_array_1 = np.sum(sum_2,axis=0) #Columns got added
print(f"{sum_array_1} \n {'-' * 40}") #Rows got added
sum_array_1 = np.sum(sum_2,axis=1)
print(sum_array_1)

[[1 2]
 [3 4]]
10 
 ----------------------------------------
[4 6] 
 ----------------------------------------
[3 7]


In [148]:
min_2 = np.array([[1,2],[3,4]])
print(min_2)
min_array_2 = np.min(min_2)
print(f"{min_array_2} \n {'-' * 40}")
min_array_2 = np.min(min_2,axis=0)  # Columns
print(f"{min_array_2} \n {'-' * 40}")
min_array_2 = np.min(min_2,axis=1)  # Rows
print(min_array_2)

[[1 2]
 [3 4]]
1 
 ----------------------------------------
[1 2] 
 ----------------------------------------
[1 3]


In [150]:
max_2 = np.array([[1,2],[3,4]])
print(max_2)
max_array_2 = np.max(max_2)
print(f"{max_array_2} \n {'-' * 40}")
max_array_2 = np.max(max_2,axis=0)  # Columns
print(f"{max_array_2} \n {'-' * 40}")
max_array_2 = np.max(max_2,axis=1)  # Rows
print(max_array_2)

[[1 2]
 [3 4]]
4 
 ----------------------------------------
[3 4] 
 ----------------------------------------
[2 4]


In [151]:
cumsum_2 = np.array([[1,2],[3,4]])
print(cumsum_2)
cumsum_array_2 = np.cumsum(cumsum_2)
print(f"{cumsum_array_2} \n {'-' * 40}")
cumsum_array_2 = np.cumsum(cumsum_2,axis=0)  # Columns
print(f"{cumsum_array_2} \n {'-' * 40}")
cumsum_array_2 = np.cumsum(cumsum_2,axis=1)  # Rows
print(cumsum_array_2)

[[1 2]
 [3 4]]
[ 1  3  6 10] 
 ----------------------------------------
[[1 2]
 [4 6]] 
 ----------------------------------------
[[1 3]
 [3 7]]


In [153]:
cumprod_2 = np.array([[1,2],[3,4]])
print(cumprod_2)
cumprod_array_2 = np.cumprod(cumprod_2)
print(f"{cumprod_array_2} \n {'-' * 40}")
cumprod_array_2 = np.cumprod(cumprod_2,axis=0)  # Columns
print(f"{cumprod_array_2} \n {'-' * 40}")
cumprod_array_2 = np.cumprod(cumprod_2,axis=1)  # Rows
print(cumprod_array_2)

[[1 2]
 [3 4]]
[ 1  2  6 24] 
 ----------------------------------------
[[1 2]
 [3 8]] 
 ----------------------------------------
[[ 1  2]
 [ 3 12]]


# 📚 Understanding Axis in 3D NumPy Arrays

A 3D NumPy array is shaped as **(D, R, C)**:
- `D`: Depth (number of slices or layers)
- `R`: Rows
- `C`: Columns

---

## 🔄 Axis Meaning in Aggregation Functions

| Axis    | Affects             | Collapses Along     |
|---------|----------------------|----------------------|
| `axis=0` | Between **slices**    | Collapses **depth**  |
| `axis=1` | Between **rows**      | Collapses **rows**   |
| `axis=2` | Between **columns**   | Collapses **columns**|

---

## 🧠 Axis Representation in 3D Arrays

| Axis    | Represents             | Example Term        |
|---------|------------------------|---------------------|
| `0`     | Layers                 | Slices / Depth      |
| `1`     | Rows per layer         | Horizontal lines    |
| `2`     | Columns per row        | Vertical lines      |

---

## 🔁 In Aggregate Functions (for 3D Arrays):

- `axis=0` → Layer-wise operation (collapses depth)
- `axis=1` → Column-wise across each layer
- `axis=2` → Row-wise across each layer

---

### 📦 Visualization

> A **3D array** is like a **stack of 2D sheets**  
> Each sheet = one layer (**axis 0**)  
> Inside each sheet:
> - Rows = **axis 1**
> - Columns = **axis 2**


In [154]:
#3D
sum_3 = np.arange(1,9).reshape(2,2,2)
print(sum_3)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
