> NumPy - Numerical PYthon
1. It`s a library consists of multidimesional array objects

> Numpy vs List

| Feature                | Python List                                        | NumPy Array                                                |
|------------------------|----------------------------------------------------|------------------------------------------------------------|
| **Data Type Support**  | Able to store different data types in the same list| Can store only one data type in an array at any time       |
| **Memory Allocation**  | Items stored in random memory locations            | Items stored sequentially in memory                        |
| **Use Case**           | Good for scenarios where list can grow dynamically | Good for scenarios with fixed-size, same data type elements|
| **Library Requirement**| Inbuilt data type                                  | Requires external NumPy library                            |
| **Functionality**      | Has more inbuilt functions                         | Lightweight with no extra functions (less memory usage)    |


<img src="https://predictivehacks.com/wp-content/uploads/2020/08/numpy_arrays.png">

1. shape(4,)       : 4 columns
2. shape:(2,3)     : 2 rows and 3 colums
3. shape:(4,3,2)   : 4 layers, 3 rows and 2 columns

> Attributes 
1. n.dim - to check the dimension
2. .shape - to print the shape
3. .dtype - To check the datatype passed in array
4. type - To check the type of array type(variable name(a))
5. len - To check the length of array len(variable name(a))


In [16]:
# For install numpy
#!pip install numpy 
#import numpy module with alias np
import numpy as np

In [17]:
#passing arry a list and string
multi_datatype = np.array([1,2,3,4,'aa'])
multi_datatype
#OUTPUT:array(['1', '2', '3', '4', 'aa'], dtype='<U21')
# converted list to string

array(['1', '2', '3', '4', 'aa'], dtype='<U21')

In [18]:
#same example tried removing string the output is LIST
list_array = np.array([1,2,3,4])
list_array
#OUTPUT: array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [19]:
tuple_array = np.array((1,2,3,4,'aa'))
tuple_array
#OUTPUT:array(['1', '2', '3', '4', 'aa'], dtype='<U21')
# converted tuple into list with strings

array(['1', '2', '3', '4', 'aa'], dtype='<U21')

In [20]:
tuple_array = np.array((1,2,3,4))
tuple_array
#OUTPUT:array([1, 2, 3, 4]), dtype='<U21')
# converted tuple into list

array([1, 2, 3, 4])

In [21]:
set_array = np.array({1,2,3,4,'aa'})
set_array
#Output:array({'aa', 2, 3, 4, 1}, dtype=object) printed as set

array({1, 2, 'aa', 3, 4}, dtype=object)

In [22]:
dict_array = np.array({1:1,2:2,3:3,4:4,'aa':1})
dict_array
#output:array({1: 1, 2: 2, 3: 3, 4: 4}, dtype=object) printed as dict

array({1: 1, 2: 2, 3: 3, 4: 4, 'aa': 1}, dtype=object)

In [23]:
list_list = np.array([1,2,3,(1,2)])
list_array
#Output->ERROR->ValueError: setting an array element with a sequence. 
# The requested array has an inhomogeneous shape after 1 dimensions. 
# The detected shape was (4,) + inhomogeneous part.

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

> Dimensions in Arrays
1. Numpy array can be of n dimentions
2. Different Dimentions
    1. A numpy array with one single interger 10 - NO Dimention
    2. A numpy array passing a list  having a list = [1,2,3] - One Dimention
    3. nested list having [[1,2,3],[4,5,6]] as elements - Two Dimention
    4. Nested list having [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]] as elements - Three Dimention
    5. ...... n dimentions
    6. we can identify the dimention with no of square brackets "[ ]"

In [ ]:
a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
## TO check the dimension use ndim attributes on each variable
print(f" Dimension a {a.ndim}")
print(f" Dimension b {b.ndim}")
print(f" Dimension c {c.ndim}")
print(f" Dimension d {d.ndim}")

 Dimension a 0
 Dimension b 1
 Dimension c 2
 Dimension d 3


In [ ]:
## print shape of each 
print(a)
print(f" shape a {a.shape}")
print("-" * 30)
print(b)
print(f" shape b {b.shape} column")
print("-" * 30)
print(c)
print(f" shape c {c.shape} rows and column")
print("-" * 30)
print(d)
print(f" shape d {d.shape} layers, rows and column")
print("-" * 30)

10
 shape a ()
------------------------------
[1 2 3]
 shape b (3,) column
------------------------------
[[1 2 3]
 [4 5 6]]
 shape c (2, 3) rows and column
------------------------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
 shape d (2, 2, 3) layers, rows and column
------------------------------


In [ ]:
# To check the datatype passed in array .dtype
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)


int64
int64
int64
int64


In [ ]:
# To check the type of array type(variable name(a))
print(type(a))
print(type(b))
print(type(c))
print(type(d))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# To check the length of array len(variable name(a))
#print(len(a)) # TypeError: len() of unsized object
print(len(b))
print(len(c))
print(len(d))

3
2
2


In [ ]:
# .arange like range function it prints 1 to 10 
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# .arange like range function it prints 1 to 10 and skip/step 2
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
#Eye Function
#.eye - eye Return a 2D array with ones on the digonal and zeros elsewhere
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
#Zero Fuction


6. .arange - like range (1,11) it prints 1 to 10 (start,stop,skip/step)
7. .eye - eye Return a 2D array with ones on the digonal and zeros elsewhere